### ISSUE TITLE
No suitable method found to override

### ISSUE THREAD

**Issue by zombikzs** [delegateas/XrmContext#28] opened 2019-11-29 11:37 UTC
Hello I generated XrmContext.cs and XrmExtension.cs file with the following command:

"C:\Dev\Project\XrmContext\XrmContext.exe" /out:"C:\Dev\Project\XrmContext\Xrm.cs" url:"https://org,api.crm4.dynamics.com/XRMServices/2011/Organization.svc" /username:user /password:password /serviceContextName:XrmServiceContext 

after that I facedmore than 48000 error on Visual Studio such as:

OpportunityCompetitors.Id: no suitable method found to override

Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error	CS0115	'Account.Id': no suitable method found to override	

Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error	CS0115	'FileAttachment.Id': no suitable method found to override

**Comment by magesoe** [comment] 2020-02-25 09:15
I just generated with these settings on 1.7.2 and got no errors, so I was unable to reproduce the issue.

If you manage to get it working I recommend using the `solutions` or `entities` parameter in order to reduce the size of your context as well as the generation time.

**Comment by bo-stig-christensen** [comment] 2020-06-29 08:42
@zombikzs : Are you still facing an issue. Just as @magesoe I cannot reproduce this and also highly recommend to reduce the context size by scoping using `solutions` and/or `entities` parameters.

Also, sometimes Visual Studio can go crazy after larger code generations and dependency changes, so a Visual Studio restart doesn't hurt and then a rebuild to verify if the issue persists.

**NB:** I am using Opportunity Competitors plugins in a larger project and having no issues.

**Comment by misoeli** [comment] 2021-06-11 11:06
Closing here. Feel free to reopen if issue persists.

**Closed by misoeli** 2021-06-11 11:06 UTC
Labels: awaiting confirmation
